# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rust语言之道
email: gudao.luo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  关注Rust语言新闻、工具、软件包和技术报道等。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cnruby
github_username:  cnruby

# Build settings
# theme: minima
theme: jekyll-theme-so-simple

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_cratess"
      type: cratess
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_tools"
      type: tools
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: "_rust"
      type: rust
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Michael Rose
  picture: /images/michael-rose-photo.jpg
  email:
  twitter: mmistakes
  links:
    - title: Twitter
      url: https://twitter.com/mmistakes
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/mmistakes
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/mmistakes
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/mmistakes
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/mmistakes
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/mmistakes
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Collections
collections:
  news:
    output: true
    permalink: /:collection/:path/
  tools:
    output: true
    permalink: /:collection/:path/
  rust:
    output: true
    permalink: /:collection/:path/
  crates:
    output: true
    permalink: /:collection/:path/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
